### ISSUE TITLE
Literature Review

### ISSUE THREAD

**Issue by pichot** [pichot/citibike-publicspace#21]
Articles, books, etc.

**Comment by kristikorsberg** [comment]
http://www.sciencedirect.com/science/article/pii/S2212827115004692

My notes:
This is a study conducted from 2011 bike sharing data in Lyon, France, which aims to quantify how the built environment impacts demand at bike sharing docks. The researchers defined built environment through public transportation, socioeconomic, topographic and bike sharing network metrics. I would say most of our variables fall under the ‘topographic’ built environment type that they’ve created. 

“The main objective of the current paper is to quantify the influence of built environment factors on arrival and departure flows at bike sharing station level using a statistical linear regression method.”

“The trips data is combined with built environment attributes around station allowing us to examine the influence of these factors on bicycle sharing demand.”

Research has already tried to predict bike sharing flow “using different urban factors such as: population, job, bicycle lanes, proximity to public transport, bike sharing station density, altitude, retail shops, etc.”

“Contributes to the literature by determining the effect of type of subscribers and built environment attributes on bicycle arrival and departure flows at the station level using hourly bike sharing data. The estimated models will allow us to predict not only the demand of bike sharing but also to better understand the influence of built environment to the bike sharing system.” 

“The hypothesis we use in this study is that the bike sharing usage of each station depends on the built environment around the station.”

“We decided to keep a 300m buffer zone because the built environment variables are the most significant in the models and a 300 meter buffer zone is an appropriate walking distance between Velo’v stations.”

“The explicative variables used in our analysis can be categorized into five groups: public transport variable, socioeconomic variable, topographic variable, bike sharing network variable, and topographic variable.”

“The number of metro, tramway and railway stations near a Velo’v station were generated to examine the influence of public transit on bike sharing flows.”

“The socio-economic variables included four factors: 1) population, 2) number of jobs, 3) number of students in campus, and 4) number of student residences near a bike sharing station.” There were a lot of students in Lyon during this study, which is why two student variables were selected here. 

They considered three types of leisure variables, “1) number of restaurants, 2) number of cinema, and 3) presence of embankment road of Rhone River – the main sportive and leisure zone near a bike sharing station.”

“Railway station is the only public transport variable that is significant in all the models of regression… metro and tramway stations are not significant in all the models.” 

“The results show also that student is an important bike sharing user. We have used two variables: the number of students on campus and the number of student residences… Bike sharing seems to be a mode of transportation well adopted by student thanks to the cheap price of subscription.”

“The variables of bike sharing network such as: bike sharing network density and capacity of station play important role in the generation of bike sharing flows. The variables are positively significant in all models. It means that the increase of number of stations and the increase of station capacity have positive impact on the bike sharing flows.”

“We observe that the bike sharing usage of long term subscribers seem not to be influenced by the leisure variables. The number of restaurants, the number of cinemas and the embankment road are not significant in any models of long term bike sharing usage. On the other hand, the bike sharing usage of short term subscribers can be described by two words: occasional and leisure.”
